# Generated by Django 4.2.5 on 2023-09-13 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('hno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('parties', models.CharField(choices=[('owner', 'owner'), ('tenant', 'tenant')], default='owner', max_length=10)),
                ('hno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='try2.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('anniversary_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField()),
                ('family_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='try2.person')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='basic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='try2.addressbasic'),
        ),
    ]
