# Generated by Django 4.2.5 on 2023-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try2', '0002_address_block_address_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbasic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
