# Generated by Django 4.2.5 on 2023-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try2', '0004_cart_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.IntegerField()),
                ('no_of_users', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('available_for', models.CharField(choices=[('owner', 'owner'), ('tenant', 'tenant')], default='owner', max_length=10)),
            ],
        ),
    ]
