# Generated by Django 4.2.5 on 2023-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try2', '0005_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
