# Generated by Django 4.2.5 on 2023-09-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try2', '0007_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='details',
            new_name='name',
        ),
    ]
